name: artifact
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: create a file
              run: |
                   mkdir build 
                   echo "This is artifact build" >> build/build.txt

            - name: upload a file
              uses: actions/upload-artifact@v7
              with:
                name: build-artifact
                path: ./build
    


    job2:
         needs: job1
         runs-on: ubuntu-latest
         steps:
            
            - name: download artifact
              uses: actions/download-artifact@v8
              with:
                name: build-artifact
                path: ./build

            - name: check files
              run: |
                   ls -lart ./build
                   cat ./build/build.txt
                  
             
            
    
            


    
             