name: outputs
on:
    push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Set a variable
          id: step1
          run: echo "msg=this is text" >> $GITHUBOUTPUT
        - name: get a variable
          run: echo "The output from step1 is ==> ${{steps.step1.outputs.msg}}"
