name: selective_jobs
on:
    workflow_dispatch:
        inputs:
            which_job_to_select:
                description: "Select jobs"
                required: true
                type: choice
                options: [job1,job2,job3,all]
     

jobs:
    job1:
        if: ${{ inputs.which_job_to_select == 'job1'|| inputs.which_job_to_select == 'all' }}
        runs-on: ubuntu-latest
        steps:
            - name: job1
              run: echo "job1 running"


    job2:
        if: ${{ inputs.which_job_to_select == 'job2'|| inputs.which_job_to_select == 'all' }}
        runs-on: ubuntu-latest
        steps:
            - name: job2
              run: echo "job2 running"
    job3:
        if: ${{ inputs.which_job_to_select == 'job3'|| inputs.which_job_to_select == 'all' }}
        runs-on: ubuntu-latest
        steps:
            - name: job3
              run: echo "job3 running"
          
          

